---
- hosts: all
  tasks:
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '{{ dir }}/ansible/id_rsa.pub') }}"

